/**
 * This class is generated by jOOQ
 */
package maxicmd.jooq.public_.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Athletes extends org.jooq.impl.TableImpl<maxicmd.jooq.public_.tables.records.AthletesRecord> {

	private static final long serialVersionUID = 1599256043;

	/**
	 * The singleton instance of <code>PUBLIC.ATHLETES</code>
	 */
	public static final maxicmd.jooq.public_.tables.Athletes ATHLETES = new maxicmd.jooq.public_.tables.Athletes();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<maxicmd.jooq.public_.tables.records.AthletesRecord> getRecordType() {
		return maxicmd.jooq.public_.tables.records.AthletesRecord.class;
	}

	/**
	 * The column <code>PUBLIC.ATHLETES.NAME</code>.
	 */
	public final org.jooq.TableField<maxicmd.jooq.public_.tables.records.AthletesRecord, java.lang.String> NAME = createField("NAME", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>PUBLIC.ATHLETES.SURNAME</code>.
	 */
	public final org.jooq.TableField<maxicmd.jooq.public_.tables.records.AthletesRecord, java.lang.String> SURNAME = createField("SURNAME", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>PUBLIC.ATHLETES.SEX</code>.
	 */
	public final org.jooq.TableField<maxicmd.jooq.public_.tables.records.AthletesRecord, java.lang.Integer> SEX = createField("SEX", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>PUBLIC.ATHLETES.AGE</code>.
	 */
	public final org.jooq.TableField<maxicmd.jooq.public_.tables.records.AthletesRecord, java.lang.Integer> AGE = createField("AGE", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>PUBLIC.ATHLETES.NATIONID</code>.
	 */
	public final org.jooq.TableField<maxicmd.jooq.public_.tables.records.AthletesRecord, java.lang.Integer> NATIONID = createField("NATIONID", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>PUBLIC.ATHLETES.OWNER</code>.
	 */
	public final org.jooq.TableField<maxicmd.jooq.public_.tables.records.AthletesRecord, java.lang.Integer> OWNER = createField("OWNER", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>PUBLIC.ATHLETES.WAGE</code>.
	 */
	public final org.jooq.TableField<maxicmd.jooq.public_.tables.records.AthletesRecord, java.lang.Integer> WAGE = createField("WAGE", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>PUBLIC.ATHLETES.HEIGHT</code>.
	 */
	public final org.jooq.TableField<maxicmd.jooq.public_.tables.records.AthletesRecord, java.lang.Integer> HEIGHT = createField("HEIGHT", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>PUBLIC.ATHLETES.WEIGHT</code>.
	 */
	public final org.jooq.TableField<maxicmd.jooq.public_.tables.records.AthletesRecord, java.lang.Integer> WEIGHT = createField("WEIGHT", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>PUBLIC.ATHLETES.FANS</code>.
	 */
	public final org.jooq.TableField<maxicmd.jooq.public_.tables.records.AthletesRecord, java.lang.Integer> FANS = createField("FANS", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>PUBLIC.ATHLETES.SPONSOR</code>.
	 */
	public final org.jooq.TableField<maxicmd.jooq.public_.tables.records.AthletesRecord, java.lang.Integer> SPONSOR = createField("SPONSOR", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>PUBLIC.ATHLETES.MAXID</code>.
	 */
	public final org.jooq.TableField<maxicmd.jooq.public_.tables.records.AthletesRecord, java.lang.Integer> MAXID = createField("MAXID", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>PUBLIC.ATHLETES.FORM</code>.
	 */
	public final org.jooq.TableField<maxicmd.jooq.public_.tables.records.AthletesRecord, java.lang.Integer> FORM = createField("FORM", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>PUBLIC.ATHLETES.CARE</code>.
	 */
	public final org.jooq.TableField<maxicmd.jooq.public_.tables.records.AthletesRecord, java.lang.Integer> CARE = createField("CARE", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>PUBLIC.ATHLETES.EXPERIENCE</code>.
	 */
	public final org.jooq.TableField<maxicmd.jooq.public_.tables.records.AthletesRecord, java.lang.Integer> EXPERIENCE = createField("EXPERIENCE", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>PUBLIC.ATHLETES.MOOD</code>.
	 */
	public final org.jooq.TableField<maxicmd.jooq.public_.tables.records.AthletesRecord, java.lang.Integer> MOOD = createField("MOOD", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>PUBLIC.ATHLETES.SPECIALTYID</code>.
	 */
	public final org.jooq.TableField<maxicmd.jooq.public_.tables.records.AthletesRecord, java.lang.Integer> SPECIALTYID = createField("SPECIALTYID", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>PUBLIC.ATHLETES.FAVORITEEVENTID</code>.
	 */
	public final org.jooq.TableField<maxicmd.jooq.public_.tables.records.AthletesRecord, java.lang.Integer> FAVORITEEVENTID = createField("FAVORITEEVENTID", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>PUBLIC.ATHLETES.STRENGHT</code>.
	 */
	public final org.jooq.TableField<maxicmd.jooq.public_.tables.records.AthletesRecord, java.lang.Integer> STRENGHT = createField("STRENGHT", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>PUBLIC.ATHLETES.STAMINA</code>.
	 */
	public final org.jooq.TableField<maxicmd.jooq.public_.tables.records.AthletesRecord, java.lang.Integer> STAMINA = createField("STAMINA", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>PUBLIC.ATHLETES.SPEED</code>.
	 */
	public final org.jooq.TableField<maxicmd.jooq.public_.tables.records.AthletesRecord, java.lang.Integer> SPEED = createField("SPEED", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>PUBLIC.ATHLETES.AGILITY</code>.
	 */
	public final org.jooq.TableField<maxicmd.jooq.public_.tables.records.AthletesRecord, java.lang.Integer> AGILITY = createField("AGILITY", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>PUBLIC.ATHLETES.JUMP</code>.
	 */
	public final org.jooq.TableField<maxicmd.jooq.public_.tables.records.AthletesRecord, java.lang.Integer> JUMP = createField("JUMP", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>PUBLIC.ATHLETES.THROW</code>.
	 */
	public final org.jooq.TableField<maxicmd.jooq.public_.tables.records.AthletesRecord, java.lang.Integer> THROW = createField("THROW", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>PUBLIC.ATHLETES.SPECIALTY1</code>.
	 */
	public final org.jooq.TableField<maxicmd.jooq.public_.tables.records.AthletesRecord, java.lang.Integer> SPECIALTY1 = createField("SPECIALTY1", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>PUBLIC.ATHLETES.SPECIALTY2</code>.
	 */
	public final org.jooq.TableField<maxicmd.jooq.public_.tables.records.AthletesRecord, java.lang.Integer> SPECIALTY2 = createField("SPECIALTY2", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>PUBLIC.ATHLETES.COACHID</code>.
	 */
	public final org.jooq.TableField<maxicmd.jooq.public_.tables.records.AthletesRecord, java.lang.Integer> COACHID = createField("COACHID", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>PUBLIC.ATHLETES.INJURY</code>.
	 */
	public final org.jooq.TableField<maxicmd.jooq.public_.tables.records.AthletesRecord, java.lang.Integer> INJURY = createField("INJURY", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>PUBLIC.ATHLETES.SELL</code>.
	 */
	public final org.jooq.TableField<maxicmd.jooq.public_.tables.records.AthletesRecord, java.lang.Integer> SELL = createField("SELL", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>PUBLIC.ATHLETES.YOUTH</code>.
	 */
	public final org.jooq.TableField<maxicmd.jooq.public_.tables.records.AthletesRecord, java.lang.Integer> YOUTH = createField("YOUTH", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>PUBLIC.ATHLETES.SPECIALTYIDTRAINED</code>.
	 */
	public final org.jooq.TableField<maxicmd.jooq.public_.tables.records.AthletesRecord, java.lang.Integer> SPECIALTYIDTRAINED = createField("SPECIALTYIDTRAINED", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>PUBLIC.ATHLETES.DIET</code>.
	 */
	public final org.jooq.TableField<maxicmd.jooq.public_.tables.records.AthletesRecord, java.lang.Integer> DIET = createField("DIET", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>PUBLIC.ATHLETES.TRAININGRETREAT</code>.
	 */
	public final org.jooq.TableField<maxicmd.jooq.public_.tables.records.AthletesRecord, java.lang.Integer> TRAININGRETREAT = createField("TRAININGRETREAT", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>PUBLIC.ATHLETES.ATHLETEID</code>.
	 */
	public final org.jooq.TableField<maxicmd.jooq.public_.tables.records.AthletesRecord, java.lang.Integer> ATHLETEID = createField("ATHLETEID", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>PUBLIC.ATHLETES.ID</code>.
	 */
	public final org.jooq.TableField<maxicmd.jooq.public_.tables.records.AthletesRecord, java.lang.Long> ID = createField("ID", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>PUBLIC.ATHLETES.CREATED</code>.
	 */
	public final org.jooq.TableField<maxicmd.jooq.public_.tables.records.AthletesRecord, java.sql.Timestamp> CREATED = createField("CREATED", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * Create a <code>PUBLIC.ATHLETES</code> table reference
	 */
	public Athletes() {
		this("ATHLETES", null);
	}

	/**
	 * Create an aliased <code>PUBLIC.ATHLETES</code> table reference
	 */
	public Athletes(java.lang.String alias) {
		this(alias, maxicmd.jooq.public_.tables.Athletes.ATHLETES);
	}

	private Athletes(java.lang.String alias, org.jooq.Table<maxicmd.jooq.public_.tables.records.AthletesRecord> aliased) {
		this(alias, aliased, null);
	}

	private Athletes(java.lang.String alias, org.jooq.Table<maxicmd.jooq.public_.tables.records.AthletesRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, maxicmd.jooq.public_.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<maxicmd.jooq.public_.tables.records.AthletesRecord, java.lang.Long> getIdentity() {
		return maxicmd.jooq.public_.Keys.IDENTITY_ATHLETES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<maxicmd.jooq.public_.tables.records.AthletesRecord> getPrimaryKey() {
		return maxicmd.jooq.public_.Keys.CONSTRAINT_A;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<maxicmd.jooq.public_.tables.records.AthletesRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<maxicmd.jooq.public_.tables.records.AthletesRecord>>asList(maxicmd.jooq.public_.Keys.CONSTRAINT_A);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public maxicmd.jooq.public_.tables.Athletes as(java.lang.String alias) {
		return new maxicmd.jooq.public_.tables.Athletes(alias, this);
	}

	/**
	 * Rename this table
	 */
	public maxicmd.jooq.public_.tables.Athletes rename(java.lang.String name) {
		return new maxicmd.jooq.public_.tables.Athletes(name, null);
	}
}
