/**
 * This class is generated by jOOQ
 */
package maxicmd.jooq.public_.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Events extends org.jooq.impl.TableImpl<maxicmd.jooq.public_.tables.records.EventsRecord> {

	private static final long serialVersionUID = -1395405723;

	/**
	 * The singleton instance of <code>PUBLIC.EVENTS</code>
	 */
	public static final maxicmd.jooq.public_.tables.Events EVENTS = new maxicmd.jooq.public_.tables.Events();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<maxicmd.jooq.public_.tables.records.EventsRecord> getRecordType() {
		return maxicmd.jooq.public_.tables.records.EventsRecord.class;
	}

	/**
	 * The column <code>PUBLIC.EVENTS.ID</code>.
	 */
	public final org.jooq.TableField<maxicmd.jooq.public_.tables.records.EventsRecord, java.lang.Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>PUBLIC.EVENTS.NAME</code>.
	 */
	public final org.jooq.TableField<maxicmd.jooq.public_.tables.records.EventsRecord, java.lang.String> NAME = createField("NAME", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

	/**
	 * Create a <code>PUBLIC.EVENTS</code> table reference
	 */
	public Events() {
		this("EVENTS", null);
	}

	/**
	 * Create an aliased <code>PUBLIC.EVENTS</code> table reference
	 */
	public Events(java.lang.String alias) {
		this(alias, maxicmd.jooq.public_.tables.Events.EVENTS);
	}

	private Events(java.lang.String alias, org.jooq.Table<maxicmd.jooq.public_.tables.records.EventsRecord> aliased) {
		this(alias, aliased, null);
	}

	private Events(java.lang.String alias, org.jooq.Table<maxicmd.jooq.public_.tables.records.EventsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, maxicmd.jooq.public_.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<maxicmd.jooq.public_.tables.records.EventsRecord> getPrimaryKey() {
		return maxicmd.jooq.public_.Keys.CONSTRAINT_7;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<maxicmd.jooq.public_.tables.records.EventsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<maxicmd.jooq.public_.tables.records.EventsRecord>>asList(maxicmd.jooq.public_.Keys.CONSTRAINT_7);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public maxicmd.jooq.public_.tables.Events as(java.lang.String alias) {
		return new maxicmd.jooq.public_.tables.Events(alias, this);
	}

	/**
	 * Rename this table
	 */
	public maxicmd.jooq.public_.tables.Events rename(java.lang.String name) {
		return new maxicmd.jooq.public_.tables.Events(name, null);
	}
}
