/**
 * This class is generated by jOOQ
 */
package maxicmd.jooq.public_.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Specialities extends org.jooq.impl.TableImpl<maxicmd.jooq.public_.tables.records.SpecialitiesRecord> {

	private static final long serialVersionUID = -296329579;

	/**
	 * The singleton instance of <code>PUBLIC.SPECIALITIES</code>
	 */
	public static final maxicmd.jooq.public_.tables.Specialities SPECIALITIES = new maxicmd.jooq.public_.tables.Specialities();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<maxicmd.jooq.public_.tables.records.SpecialitiesRecord> getRecordType() {
		return maxicmd.jooq.public_.tables.records.SpecialitiesRecord.class;
	}

	/**
	 * The column <code>PUBLIC.SPECIALITIES.ID</code>.
	 */
	public final org.jooq.TableField<maxicmd.jooq.public_.tables.records.SpecialitiesRecord, java.lang.Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>PUBLIC.SPECIALITIES.NAME</code>.
	 */
	public final org.jooq.TableField<maxicmd.jooq.public_.tables.records.SpecialitiesRecord, java.lang.String> NAME = createField("NAME", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

	/**
	 * Create a <code>PUBLIC.SPECIALITIES</code> table reference
	 */
	public Specialities() {
		this("SPECIALITIES", null);
	}

	/**
	 * Create an aliased <code>PUBLIC.SPECIALITIES</code> table reference
	 */
	public Specialities(java.lang.String alias) {
		this(alias, maxicmd.jooq.public_.tables.Specialities.SPECIALITIES);
	}

	private Specialities(java.lang.String alias, org.jooq.Table<maxicmd.jooq.public_.tables.records.SpecialitiesRecord> aliased) {
		this(alias, aliased, null);
	}

	private Specialities(java.lang.String alias, org.jooq.Table<maxicmd.jooq.public_.tables.records.SpecialitiesRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, maxicmd.jooq.public_.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<maxicmd.jooq.public_.tables.records.SpecialitiesRecord> getPrimaryKey() {
		return maxicmd.jooq.public_.Keys.CONSTRAINT_E;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<maxicmd.jooq.public_.tables.records.SpecialitiesRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<maxicmd.jooq.public_.tables.records.SpecialitiesRecord>>asList(maxicmd.jooq.public_.Keys.CONSTRAINT_E);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public maxicmd.jooq.public_.tables.Specialities as(java.lang.String alias) {
		return new maxicmd.jooq.public_.tables.Specialities(alias, this);
	}

	/**
	 * Rename this table
	 */
	public maxicmd.jooq.public_.tables.Specialities rename(java.lang.String name) {
		return new maxicmd.jooq.public_.tables.Specialities(name, null);
	}
}
