/**
 * This class is generated by jOOQ
 */
package maxicmd.jooq;

/**
 * This class is generated by jOOQ.
 *
 * A class modelling foreign key relationships between tables of the <code>public</code> 
 * schema
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.Identity<maxicmd.jooq.tables.records.AthleteRecord, java.lang.Integer> IDENTITY_ATHLETE = Identities0.IDENTITY_ATHLETE;
	public static final org.jooq.Identity<maxicmd.jooq.tables.records.ImportHistoryRecord, java.lang.Integer> IDENTITY_IMPORT_HISTORY = Identities0.IDENTITY_IMPORT_HISTORY;

	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.UniqueKey<maxicmd.jooq.tables.records.AthleteRecord> ATHLETE_PK = UniqueKeys0.ATHLETE_PK;
	public static final org.jooq.UniqueKey<maxicmd.jooq.tables.records.AttitudeRecord> ATTITUDE_PK = UniqueKeys0.ATTITUDE_PK;
	public static final org.jooq.UniqueKey<maxicmd.jooq.tables.records.CompetitionStatusRecord> COMPETITION_STATUS_PK = UniqueKeys0.COMPETITION_STATUS_PK;
	public static final org.jooq.UniqueKey<maxicmd.jooq.tables.records.CompetitionTypeRecord> COMPETITION_TYPE_PK = UniqueKeys0.COMPETITION_TYPE_PK;
	public static final org.jooq.UniqueKey<maxicmd.jooq.tables.records.DietRecord> DIED_PK = UniqueKeys0.DIED_PK;
	public static final org.jooq.UniqueKey<maxicmd.jooq.tables.records.EventRecord> EVENT_PK = UniqueKeys0.EVENT_PK;
	public static final org.jooq.UniqueKey<maxicmd.jooq.tables.records.ImportHistoryRecord> IMPORT_HISTORY_FILENAME_UQ = UniqueKeys0.IMPORT_HISTORY_FILENAME_UQ;
	public static final org.jooq.UniqueKey<maxicmd.jooq.tables.records.ImportHistoryRecord> IMPORT_HISTORY_PK = UniqueKeys0.IMPORT_HISTORY_PK;
	public static final org.jooq.UniqueKey<maxicmd.jooq.tables.records.MeteoRecord> METEO_PK = UniqueKeys0.METEO_PK;
	public static final org.jooq.UniqueKey<maxicmd.jooq.tables.records.SpecialtyRecord> SPECIALITY_PK = UniqueKeys0.SPECIALITY_PK;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------


	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class Identities0 extends org.jooq.impl.AbstractKeys {
		public static org.jooq.Identity<maxicmd.jooq.tables.records.AthleteRecord, java.lang.Integer> IDENTITY_ATHLETE = createIdentity(maxicmd.jooq.tables.Athlete.ATHLETE, maxicmd.jooq.tables.Athlete.ATHLETE.ID);
		public static org.jooq.Identity<maxicmd.jooq.tables.records.ImportHistoryRecord, java.lang.Integer> IDENTITY_IMPORT_HISTORY = createIdentity(maxicmd.jooq.tables.ImportHistory.IMPORT_HISTORY, maxicmd.jooq.tables.ImportHistory.IMPORT_HISTORY.ID);
	}

	private static class UniqueKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.UniqueKey<maxicmd.jooq.tables.records.AthleteRecord> ATHLETE_PK = createUniqueKey(maxicmd.jooq.tables.Athlete.ATHLETE, maxicmd.jooq.tables.Athlete.ATHLETE.ID);
		public static final org.jooq.UniqueKey<maxicmd.jooq.tables.records.AttitudeRecord> ATTITUDE_PK = createUniqueKey(maxicmd.jooq.tables.Attitude.ATTITUDE, maxicmd.jooq.tables.Attitude.ATTITUDE.ID);
		public static final org.jooq.UniqueKey<maxicmd.jooq.tables.records.CompetitionStatusRecord> COMPETITION_STATUS_PK = createUniqueKey(maxicmd.jooq.tables.CompetitionStatus.COMPETITION_STATUS, maxicmd.jooq.tables.CompetitionStatus.COMPETITION_STATUS.ID);
		public static final org.jooq.UniqueKey<maxicmd.jooq.tables.records.CompetitionTypeRecord> COMPETITION_TYPE_PK = createUniqueKey(maxicmd.jooq.tables.CompetitionType.COMPETITION_TYPE, maxicmd.jooq.tables.CompetitionType.COMPETITION_TYPE.ID);
		public static final org.jooq.UniqueKey<maxicmd.jooq.tables.records.DietRecord> DIED_PK = createUniqueKey(maxicmd.jooq.tables.Diet.DIET, maxicmd.jooq.tables.Diet.DIET.ID);
		public static final org.jooq.UniqueKey<maxicmd.jooq.tables.records.EventRecord> EVENT_PK = createUniqueKey(maxicmd.jooq.tables.Event.EVENT, maxicmd.jooq.tables.Event.EVENT.ID);
		public static final org.jooq.UniqueKey<maxicmd.jooq.tables.records.ImportHistoryRecord> IMPORT_HISTORY_FILENAME_UQ = createUniqueKey(maxicmd.jooq.tables.ImportHistory.IMPORT_HISTORY, maxicmd.jooq.tables.ImportHistory.IMPORT_HISTORY.FILENAME);
		public static final org.jooq.UniqueKey<maxicmd.jooq.tables.records.ImportHistoryRecord> IMPORT_HISTORY_PK = createUniqueKey(maxicmd.jooq.tables.ImportHistory.IMPORT_HISTORY, maxicmd.jooq.tables.ImportHistory.IMPORT_HISTORY.ID);
		public static final org.jooq.UniqueKey<maxicmd.jooq.tables.records.MeteoRecord> METEO_PK = createUniqueKey(maxicmd.jooq.tables.Meteo.METEO, maxicmd.jooq.tables.Meteo.METEO.ID);
		public static final org.jooq.UniqueKey<maxicmd.jooq.tables.records.SpecialtyRecord> SPECIALITY_PK = createUniqueKey(maxicmd.jooq.tables.Specialty.SPECIALTY, maxicmd.jooq.tables.Specialty.SPECIALTY.ID);
	}
}
