/**
 * This class is generated by jOOQ
 */
package maxicmd.jooq;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends org.jooq.impl.SchemaImpl {

	private static final long serialVersionUID = -1743777664;

	/**
	 * The singleton instance of <code>public</code>
	 */
	public static final Public PUBLIC = new Public();

	/**
	 * No further instances allowed
	 */
	private Public() {
		super("public");
	}

	@Override
	public final java.util.List<org.jooq.Sequence<?>> getSequences() {
		java.util.List result = new java.util.ArrayList();
		result.addAll(getSequences0());
		return result;
	}

	private final java.util.List<org.jooq.Sequence<?>> getSequences0() {
		return java.util.Arrays.<org.jooq.Sequence<?>>asList(
			maxicmd.jooq.Sequences.ATHLETE_ID_SEQ,
			maxicmd.jooq.Sequences.IMPORT_HISTORY_ID_SEQ);
	}

	@Override
	public final java.util.List<org.jooq.Table<?>> getTables() {
		java.util.List result = new java.util.ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final java.util.List<org.jooq.Table<?>> getTables0() {
		return java.util.Arrays.<org.jooq.Table<?>>asList(
			maxicmd.jooq.tables.Athlete.ATHLETE,
			maxicmd.jooq.tables.Attitude.ATTITUDE,
			maxicmd.jooq.tables.CompetitionStatus.COMPETITION_STATUS,
			maxicmd.jooq.tables.CompetitionType.COMPETITION_TYPE,
			maxicmd.jooq.tables.Diet.DIET,
			maxicmd.jooq.tables.Event.EVENT,
			maxicmd.jooq.tables.ImportHistory.IMPORT_HISTORY,
			maxicmd.jooq.tables.Meteo.METEO,
			maxicmd.jooq.tables.Specialty.SPECIALTY);
	}
}
