/**
 * This class is generated by jOOQ
 */
package maxicmd.jooq;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all sequences in public
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

	/**
	 * The sequence <code>public.athlete_id_seq</code>
	 */
	public static final org.jooq.Sequence<java.lang.Long> ATHLETE_ID_SEQ = new org.jooq.impl.SequenceImpl<java.lang.Long>("athlete_id_seq", maxicmd.jooq.Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.import_history_id_seq</code>
	 */
	public static final org.jooq.Sequence<java.lang.Long> IMPORT_HISTORY_ID_SEQ = new org.jooq.impl.SequenceImpl<java.lang.Long>("import_history_id_seq", maxicmd.jooq.Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));
}
