/**
 * This class is generated by jOOQ
 */
package maxicmd.jooq;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in public
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table public.athlete
	 */
	public static final maxicmd.jooq.tables.Athlete ATHLETE = maxicmd.jooq.tables.Athlete.ATHLETE;

	/**
	 * The table public.attitude
	 */
	public static final maxicmd.jooq.tables.Attitude ATTITUDE = maxicmd.jooq.tables.Attitude.ATTITUDE;

	/**
	 * The table public.competition_status
	 */
	public static final maxicmd.jooq.tables.CompetitionStatus COMPETITION_STATUS = maxicmd.jooq.tables.CompetitionStatus.COMPETITION_STATUS;

	/**
	 * The table public.competition_type
	 */
	public static final maxicmd.jooq.tables.CompetitionType COMPETITION_TYPE = maxicmd.jooq.tables.CompetitionType.COMPETITION_TYPE;

	/**
	 * The table public.diet
	 */
	public static final maxicmd.jooq.tables.Diet DIET = maxicmd.jooq.tables.Diet.DIET;

	/**
	 * The table public.event
	 */
	public static final maxicmd.jooq.tables.Event EVENT = maxicmd.jooq.tables.Event.EVENT;

	/**
	 * The table public.import_history
	 */
	public static final maxicmd.jooq.tables.ImportHistory IMPORT_HISTORY = maxicmd.jooq.tables.ImportHistory.IMPORT_HISTORY;

	/**
	 * The table public.meteo
	 */
	public static final maxicmd.jooq.tables.Meteo METEO = maxicmd.jooq.tables.Meteo.METEO;

	/**
	 * The table public.specialty
	 */
	public static final maxicmd.jooq.tables.Specialty SPECIALTY = maxicmd.jooq.tables.Specialty.SPECIALTY;
}
