/**
 * This class is generated by jOOQ
 */
package maxicmd.jooq.public_;

/**
 * This class is generated by jOOQ.
 *
 * A class modelling foreign key relationships between tables of the <code>PUBLIC</code> 
 * schema
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.Identity<maxicmd.jooq.public_.tables.records.AthletesRecord, java.lang.Long> IDENTITY_ATHLETES = Identities0.IDENTITY_ATHLETES;

	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.UniqueKey<maxicmd.jooq.public_.tables.records.AthletesRecord> CONSTRAINT_A = UniqueKeys0.CONSTRAINT_A;
	public static final org.jooq.UniqueKey<maxicmd.jooq.public_.tables.records.SpecialitiesRecord> CONSTRAINT_E = UniqueKeys0.CONSTRAINT_E;
	public static final org.jooq.UniqueKey<maxicmd.jooq.public_.tables.records.EventsRecord> CONSTRAINT_7 = UniqueKeys0.CONSTRAINT_7;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------


	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class Identities0 extends org.jooq.impl.AbstractKeys {
		public static org.jooq.Identity<maxicmd.jooq.public_.tables.records.AthletesRecord, java.lang.Long> IDENTITY_ATHLETES = createIdentity(maxicmd.jooq.public_.tables.Athletes.ATHLETES, maxicmd.jooq.public_.tables.Athletes.ATHLETES.ID);
	}

	private static class UniqueKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.UniqueKey<maxicmd.jooq.public_.tables.records.AthletesRecord> CONSTRAINT_A = createUniqueKey(maxicmd.jooq.public_.tables.Athletes.ATHLETES, maxicmd.jooq.public_.tables.Athletes.ATHLETES.ID);
		public static final org.jooq.UniqueKey<maxicmd.jooq.public_.tables.records.SpecialitiesRecord> CONSTRAINT_E = createUniqueKey(maxicmd.jooq.public_.tables.Specialities.SPECIALITIES, maxicmd.jooq.public_.tables.Specialities.SPECIALITIES.ID);
		public static final org.jooq.UniqueKey<maxicmd.jooq.public_.tables.records.EventsRecord> CONSTRAINT_7 = createUniqueKey(maxicmd.jooq.public_.tables.Events.EVENTS, maxicmd.jooq.public_.tables.Events.EVENTS.ID);
	}
}
