/**
 * This class is generated by jOOQ
 */
package maxicmd.jooq.public_;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all sequences in PUBLIC
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

	/**
	 * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_DAC3FB81_F6B8_419E_9067_4FDBEB2883FA</code>
	 */
	public static final org.jooq.Sequence<java.lang.Long> SYSTEM_SEQUENCE_DAC3FB81_F6B8_419E_9067_4FDBEB2883FA = new org.jooq.impl.SequenceImpl<java.lang.Long>("SYSTEM_SEQUENCE_DAC3FB81_F6B8_419E_9067_4FDBEB2883FA", maxicmd.jooq.public_.Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);
}
