/**
 * This class is generated by jOOQ
 */
package maxicmd.jooq.public_;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in PUBLIC
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table PUBLIC.ATHLETES
	 */
	public static final maxicmd.jooq.public_.tables.Athletes ATHLETES = maxicmd.jooq.public_.tables.Athletes.ATHLETES;

	/**
	 * The table PUBLIC.SPECIALITIES
	 */
	public static final maxicmd.jooq.public_.tables.Specialities SPECIALITIES = maxicmd.jooq.public_.tables.Specialities.SPECIALITIES;

	/**
	 * The table PUBLIC.EVENTS
	 */
	public static final maxicmd.jooq.public_.tables.Events EVENTS = maxicmd.jooq.public_.tables.Events.EVENTS;
}
