/**
 * This class is generated by jOOQ
 */
package maxicmd.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Athlete extends org.jooq.impl.TableImpl<maxicmd.jooq.tables.records.AthleteRecord> {

	private static final long serialVersionUID = 2055881841;

	/**
	 * The singleton instance of <code>public.athlete</code>
	 */
	public static final maxicmd.jooq.tables.Athlete ATHLETE = new maxicmd.jooq.tables.Athlete();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<maxicmd.jooq.tables.records.AthleteRecord> getRecordType() {
		return maxicmd.jooq.tables.records.AthleteRecord.class;
	}

	/**
	 * The column <code>public.athlete.athleteid</code>.
	 */
	public final org.jooq.TableField<maxicmd.jooq.tables.records.AthleteRecord, java.lang.Integer> ATHLETEID = createField("athleteid", org.jooq.impl.SQLDataType.INTEGER.defaulted(true), this, "");

	/**
	 * The column <code>public.athlete.name</code>.
	 */
	public final org.jooq.TableField<maxicmd.jooq.tables.records.AthleteRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(50).defaulted(true), this, "");

	/**
	 * The column <code>public.athlete.surname</code>.
	 */
	public final org.jooq.TableField<maxicmd.jooq.tables.records.AthleteRecord, java.lang.String> SURNAME = createField("surname", org.jooq.impl.SQLDataType.VARCHAR.length(50).defaulted(true), this, "");

	/**
	 * The column <code>public.athlete.sex</code>.
	 */
	public final org.jooq.TableField<maxicmd.jooq.tables.records.AthleteRecord, java.lang.Integer> SEX = createField("sex", org.jooq.impl.SQLDataType.INTEGER.defaulted(true), this, "");

	/**
	 * The column <code>public.athlete.nationid</code>.
	 */
	public final org.jooq.TableField<maxicmd.jooq.tables.records.AthleteRecord, java.lang.Integer> NATIONID = createField("nationid", org.jooq.impl.SQLDataType.INTEGER.defaulted(true), this, "");

	/**
	 * The column <code>public.athlete.owner</code>.
	 */
	public final org.jooq.TableField<maxicmd.jooq.tables.records.AthleteRecord, java.lang.Integer> OWNER = createField("owner", org.jooq.impl.SQLDataType.INTEGER.defaulted(true), this, "");

	/**
	 * The column <code>public.athlete.wage</code>.
	 */
	public final org.jooq.TableField<maxicmd.jooq.tables.records.AthleteRecord, java.lang.Integer> WAGE = createField("wage", org.jooq.impl.SQLDataType.INTEGER.defaulted(true), this, "");

	/**
	 * The column <code>public.athlete.height</code>.
	 */
	public final org.jooq.TableField<maxicmd.jooq.tables.records.AthleteRecord, java.lang.Integer> HEIGHT = createField("height", org.jooq.impl.SQLDataType.INTEGER.defaulted(true), this, "");

	/**
	 * The column <code>public.athlete.weight</code>.
	 */
	public final org.jooq.TableField<maxicmd.jooq.tables.records.AthleteRecord, java.lang.Integer> WEIGHT = createField("weight", org.jooq.impl.SQLDataType.INTEGER.defaulted(true), this, "");

	/**
	 * The column <code>public.athlete.fans</code>.
	 */
	public final org.jooq.TableField<maxicmd.jooq.tables.records.AthleteRecord, java.lang.Integer> FANS = createField("fans", org.jooq.impl.SQLDataType.INTEGER.defaulted(true), this, "");

	/**
	 * The column <code>public.athlete.maxid</code>.
	 */
	public final org.jooq.TableField<maxicmd.jooq.tables.records.AthleteRecord, java.lang.Integer> MAXID = createField("maxid", org.jooq.impl.SQLDataType.INTEGER.defaulted(true), this, "");

	/**
	 * The column <code>public.athlete.form</code>.
	 */
	public final org.jooq.TableField<maxicmd.jooq.tables.records.AthleteRecord, java.lang.Integer> FORM = createField("form", org.jooq.impl.SQLDataType.INTEGER.defaulted(true), this, "");

	/**
	 * The column <code>public.athlete.care</code>.
	 */
	public final org.jooq.TableField<maxicmd.jooq.tables.records.AthleteRecord, java.lang.Integer> CARE = createField("care", org.jooq.impl.SQLDataType.INTEGER.defaulted(true), this, "");

	/**
	 * The column <code>public.athlete.experience</code>.
	 */
	public final org.jooq.TableField<maxicmd.jooq.tables.records.AthleteRecord, java.lang.Integer> EXPERIENCE = createField("experience", org.jooq.impl.SQLDataType.INTEGER.defaulted(true), this, "");

	/**
	 * The column <code>public.athlete.mood</code>.
	 */
	public final org.jooq.TableField<maxicmd.jooq.tables.records.AthleteRecord, java.lang.Integer> MOOD = createField("mood", org.jooq.impl.SQLDataType.INTEGER.defaulted(true), this, "");

	/**
	 * The column <code>public.athlete.specialtyid</code>.
	 */
	public final org.jooq.TableField<maxicmd.jooq.tables.records.AthleteRecord, java.lang.Integer> SPECIALTYID = createField("specialtyid", org.jooq.impl.SQLDataType.INTEGER.defaulted(true), this, "");

	/**
	 * The column <code>public.athlete.favoriteeventid</code>.
	 */
	public final org.jooq.TableField<maxicmd.jooq.tables.records.AthleteRecord, java.lang.Integer> FAVORITEEVENTID = createField("favoriteeventid", org.jooq.impl.SQLDataType.INTEGER.defaulted(true), this, "");

	/**
	 * The column <code>public.athlete.strenght</code>.
	 */
	public final org.jooq.TableField<maxicmd.jooq.tables.records.AthleteRecord, java.lang.Integer> STRENGHT = createField("strenght", org.jooq.impl.SQLDataType.INTEGER.defaulted(true), this, "");

	/**
	 * The column <code>public.athlete.stamina</code>.
	 */
	public final org.jooq.TableField<maxicmd.jooq.tables.records.AthleteRecord, java.lang.Integer> STAMINA = createField("stamina", org.jooq.impl.SQLDataType.INTEGER.defaulted(true), this, "");

	/**
	 * The column <code>public.athlete.speed</code>.
	 */
	public final org.jooq.TableField<maxicmd.jooq.tables.records.AthleteRecord, java.lang.Integer> SPEED = createField("speed", org.jooq.impl.SQLDataType.INTEGER.defaulted(true), this, "");

	/**
	 * The column <code>public.athlete.agility</code>.
	 */
	public final org.jooq.TableField<maxicmd.jooq.tables.records.AthleteRecord, java.lang.Integer> AGILITY = createField("agility", org.jooq.impl.SQLDataType.INTEGER.defaulted(true), this, "");

	/**
	 * The column <code>public.athlete.jump</code>.
	 */
	public final org.jooq.TableField<maxicmd.jooq.tables.records.AthleteRecord, java.lang.Integer> JUMP = createField("jump", org.jooq.impl.SQLDataType.INTEGER.defaulted(true), this, "");

	/**
	 * The column <code>public.athlete.throw</code>.
	 */
	public final org.jooq.TableField<maxicmd.jooq.tables.records.AthleteRecord, java.lang.Integer> THROW = createField("throw", org.jooq.impl.SQLDataType.INTEGER.defaulted(true), this, "");

	/**
	 * The column <code>public.athlete.specialty1</code>.
	 */
	public final org.jooq.TableField<maxicmd.jooq.tables.records.AthleteRecord, java.lang.Integer> SPECIALTY1 = createField("specialty1", org.jooq.impl.SQLDataType.INTEGER.defaulted(true), this, "");

	/**
	 * The column <code>public.athlete.specialty2</code>.
	 */
	public final org.jooq.TableField<maxicmd.jooq.tables.records.AthleteRecord, java.lang.Integer> SPECIALTY2 = createField("specialty2", org.jooq.impl.SQLDataType.INTEGER.defaulted(true), this, "");

	/**
	 * The column <code>public.athlete.coachid</code>.
	 */
	public final org.jooq.TableField<maxicmd.jooq.tables.records.AthleteRecord, java.lang.Integer> COACHID = createField("coachid", org.jooq.impl.SQLDataType.INTEGER.defaulted(true), this, "");

	/**
	 * The column <code>public.athlete.injury</code>.
	 */
	public final org.jooq.TableField<maxicmd.jooq.tables.records.AthleteRecord, java.lang.Integer> INJURY = createField("injury", org.jooq.impl.SQLDataType.INTEGER.defaulted(true), this, "");

	/**
	 * The column <code>public.athlete.date</code>.
	 */
	public final org.jooq.TableField<maxicmd.jooq.tables.records.AthleteRecord, java.sql.Time> DATE = createField("date", org.jooq.impl.SQLDataType.TIME.defaulted(true), this, "");

	/**
	 * The column <code>public.athlete.id</code>.
	 */
	public final org.jooq.TableField<maxicmd.jooq.tables.records.AthleteRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.athlete.age</code>.
	 */
	public final org.jooq.TableField<maxicmd.jooq.tables.records.AthleteRecord, java.lang.Integer> AGE = createField("age", org.jooq.impl.SQLDataType.INTEGER.defaulted(true), this, "");

	/**
	 * The column <code>public.athlete.youth</code>.
	 */
	public final org.jooq.TableField<maxicmd.jooq.tables.records.AthleteRecord, java.lang.Integer> YOUTH = createField("youth", org.jooq.impl.SQLDataType.INTEGER.defaulted(true), this, "");

	/**
	 * The column <code>public.athlete.specialtyidtrained</code>.
	 */
	public final org.jooq.TableField<maxicmd.jooq.tables.records.AthleteRecord, java.lang.Integer> SPECIALTYIDTRAINED = createField("specialtyidtrained", org.jooq.impl.SQLDataType.INTEGER.defaulted(true), this, "");

	/**
	 * The column <code>public.athlete.diet</code>.
	 */
	public final org.jooq.TableField<maxicmd.jooq.tables.records.AthleteRecord, java.lang.Integer> DIET = createField("diet", org.jooq.impl.SQLDataType.INTEGER.defaulted(true), this, "");

	/**
	 * The column <code>public.athlete.trainingretreat</code>.
	 */
	public final org.jooq.TableField<maxicmd.jooq.tables.records.AthleteRecord, java.lang.Integer> TRAININGRETREAT = createField("trainingretreat", org.jooq.impl.SQLDataType.INTEGER.defaulted(true), this, "");

	/**
	 * Create a <code>public.athlete</code> table reference
	 */
	public Athlete() {
		this("athlete", null);
	}

	/**
	 * Create an aliased <code>public.athlete</code> table reference
	 */
	public Athlete(java.lang.String alias) {
		this(alias, maxicmd.jooq.tables.Athlete.ATHLETE);
	}

	private Athlete(java.lang.String alias, org.jooq.Table<maxicmd.jooq.tables.records.AthleteRecord> aliased) {
		this(alias, aliased, null);
	}

	private Athlete(java.lang.String alias, org.jooq.Table<maxicmd.jooq.tables.records.AthleteRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, maxicmd.jooq.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<maxicmd.jooq.tables.records.AthleteRecord, java.lang.Integer> getIdentity() {
		return maxicmd.jooq.Keys.IDENTITY_ATHLETE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<maxicmd.jooq.tables.records.AthleteRecord> getPrimaryKey() {
		return maxicmd.jooq.Keys.ATHLETE_PK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<maxicmd.jooq.tables.records.AthleteRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<maxicmd.jooq.tables.records.AthleteRecord>>asList(maxicmd.jooq.Keys.ATHLETE_PK);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public maxicmd.jooq.tables.Athlete as(java.lang.String alias) {
		return new maxicmd.jooq.tables.Athlete(alias, this);
	}

	/**
	 * Rename this table
	 */
	public maxicmd.jooq.tables.Athlete rename(java.lang.String name) {
		return new maxicmd.jooq.tables.Athlete(name, null);
	}
}
