/**
 * This class is generated by jOOQ
 */
package maxicmd.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Attitude extends org.jooq.impl.TableImpl<maxicmd.jooq.tables.records.AttitudeRecord> {

	private static final long serialVersionUID = -167053784;

	/**
	 * The singleton instance of <code>public.attitude</code>
	 */
	public static final maxicmd.jooq.tables.Attitude ATTITUDE = new maxicmd.jooq.tables.Attitude();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<maxicmd.jooq.tables.records.AttitudeRecord> getRecordType() {
		return maxicmd.jooq.tables.records.AttitudeRecord.class;
	}

	/**
	 * The column <code>public.attitude.id</code>.
	 */
	public final org.jooq.TableField<maxicmd.jooq.tables.records.AttitudeRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.attitude.name</code>.
	 */
	public final org.jooq.TableField<maxicmd.jooq.tables.records.AttitudeRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(255).defaulted(true), this, "");

	/**
	 * Create a <code>public.attitude</code> table reference
	 */
	public Attitude() {
		this("attitude", null);
	}

	/**
	 * Create an aliased <code>public.attitude</code> table reference
	 */
	public Attitude(java.lang.String alias) {
		this(alias, maxicmd.jooq.tables.Attitude.ATTITUDE);
	}

	private Attitude(java.lang.String alias, org.jooq.Table<maxicmd.jooq.tables.records.AttitudeRecord> aliased) {
		this(alias, aliased, null);
	}

	private Attitude(java.lang.String alias, org.jooq.Table<maxicmd.jooq.tables.records.AttitudeRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, maxicmd.jooq.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<maxicmd.jooq.tables.records.AttitudeRecord> getPrimaryKey() {
		return maxicmd.jooq.Keys.ATTITUDE_PK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<maxicmd.jooq.tables.records.AttitudeRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<maxicmd.jooq.tables.records.AttitudeRecord>>asList(maxicmd.jooq.Keys.ATTITUDE_PK);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public maxicmd.jooq.tables.Attitude as(java.lang.String alias) {
		return new maxicmd.jooq.tables.Attitude(alias, this);
	}

	/**
	 * Rename this table
	 */
	public maxicmd.jooq.tables.Attitude rename(java.lang.String name) {
		return new maxicmd.jooq.tables.Attitude(name, null);
	}
}
