/**
 * This class is generated by jOOQ
 */
package maxicmd.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ImportHistory extends org.jooq.impl.TableImpl<maxicmd.jooq.tables.records.ImportHistoryRecord> {

	private static final long serialVersionUID = -170505127;

	/**
	 * The singleton instance of <code>public.import_history</code>
	 */
	public static final maxicmd.jooq.tables.ImportHistory IMPORT_HISTORY = new maxicmd.jooq.tables.ImportHistory();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<maxicmd.jooq.tables.records.ImportHistoryRecord> getRecordType() {
		return maxicmd.jooq.tables.records.ImportHistoryRecord.class;
	}

	/**
	 * The column <code>public.import_history.filename</code>.
	 */
	public final org.jooq.TableField<maxicmd.jooq.tables.records.ImportHistoryRecord, java.lang.String> FILENAME = createField("filename", org.jooq.impl.SQLDataType.VARCHAR.length(255).defaulted(true), this, "");

	/**
	 * The column <code>public.import_history.timestamp</code>.
	 */
	public final org.jooq.TableField<maxicmd.jooq.tables.records.ImportHistoryRecord, java.sql.Timestamp> TIMESTAMP = createField("timestamp", org.jooq.impl.SQLDataType.TIMESTAMP.defaulted(true), this, "");

	/**
	 * The column <code>public.import_history.id</code>.
	 */
	public final org.jooq.TableField<maxicmd.jooq.tables.records.ImportHistoryRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * Create a <code>public.import_history</code> table reference
	 */
	public ImportHistory() {
		this("import_history", null);
	}

	/**
	 * Create an aliased <code>public.import_history</code> table reference
	 */
	public ImportHistory(java.lang.String alias) {
		this(alias, maxicmd.jooq.tables.ImportHistory.IMPORT_HISTORY);
	}

	private ImportHistory(java.lang.String alias, org.jooq.Table<maxicmd.jooq.tables.records.ImportHistoryRecord> aliased) {
		this(alias, aliased, null);
	}

	private ImportHistory(java.lang.String alias, org.jooq.Table<maxicmd.jooq.tables.records.ImportHistoryRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, maxicmd.jooq.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<maxicmd.jooq.tables.records.ImportHistoryRecord, java.lang.Integer> getIdentity() {
		return maxicmd.jooq.Keys.IDENTITY_IMPORT_HISTORY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<maxicmd.jooq.tables.records.ImportHistoryRecord> getPrimaryKey() {
		return maxicmd.jooq.Keys.IMPORT_HISTORY_PK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<maxicmd.jooq.tables.records.ImportHistoryRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<maxicmd.jooq.tables.records.ImportHistoryRecord>>asList(maxicmd.jooq.Keys.IMPORT_HISTORY_FILENAME_UQ, maxicmd.jooq.Keys.IMPORT_HISTORY_PK);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public maxicmd.jooq.tables.ImportHistory as(java.lang.String alias) {
		return new maxicmd.jooq.tables.ImportHistory(alias, this);
	}

	/**
	 * Rename this table
	 */
	public maxicmd.jooq.tables.ImportHistory rename(java.lang.String name) {
		return new maxicmd.jooq.tables.ImportHistory(name, null);
	}
}
