/**
 * This class is generated by jOOQ
 */
package maxicmd.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Meteo extends org.jooq.impl.TableImpl<maxicmd.jooq.tables.records.MeteoRecord> {

	private static final long serialVersionUID = -784781138;

	/**
	 * The singleton instance of <code>public.meteo</code>
	 */
	public static final maxicmd.jooq.tables.Meteo METEO = new maxicmd.jooq.tables.Meteo();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<maxicmd.jooq.tables.records.MeteoRecord> getRecordType() {
		return maxicmd.jooq.tables.records.MeteoRecord.class;
	}

	/**
	 * The column <code>public.meteo.id</code>.
	 */
	public final org.jooq.TableField<maxicmd.jooq.tables.records.MeteoRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.meteo.name</code>.
	 */
	public final org.jooq.TableField<maxicmd.jooq.tables.records.MeteoRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(255).defaulted(true), this, "");

	/**
	 * Create a <code>public.meteo</code> table reference
	 */
	public Meteo() {
		this("meteo", null);
	}

	/**
	 * Create an aliased <code>public.meteo</code> table reference
	 */
	public Meteo(java.lang.String alias) {
		this(alias, maxicmd.jooq.tables.Meteo.METEO);
	}

	private Meteo(java.lang.String alias, org.jooq.Table<maxicmd.jooq.tables.records.MeteoRecord> aliased) {
		this(alias, aliased, null);
	}

	private Meteo(java.lang.String alias, org.jooq.Table<maxicmd.jooq.tables.records.MeteoRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, maxicmd.jooq.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<maxicmd.jooq.tables.records.MeteoRecord> getPrimaryKey() {
		return maxicmd.jooq.Keys.METEO_PK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<maxicmd.jooq.tables.records.MeteoRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<maxicmd.jooq.tables.records.MeteoRecord>>asList(maxicmd.jooq.Keys.METEO_PK);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public maxicmd.jooq.tables.Meteo as(java.lang.String alias) {
		return new maxicmd.jooq.tables.Meteo(alias, this);
	}

	/**
	 * Rename this table
	 */
	public maxicmd.jooq.tables.Meteo rename(java.lang.String name) {
		return new maxicmd.jooq.tables.Meteo(name, null);
	}
}
