/**
 * This class is generated by jOOQ
 */
package maxicmd.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Specialty extends org.jooq.impl.TableImpl<maxicmd.jooq.tables.records.SpecialtyRecord> {

	private static final long serialVersionUID = 100910092;

	/**
	 * The singleton instance of <code>public.specialty</code>
	 */
	public static final maxicmd.jooq.tables.Specialty SPECIALTY = new maxicmd.jooq.tables.Specialty();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<maxicmd.jooq.tables.records.SpecialtyRecord> getRecordType() {
		return maxicmd.jooq.tables.records.SpecialtyRecord.class;
	}

	/**
	 * The column <code>public.specialty.id</code>.
	 */
	public final org.jooq.TableField<maxicmd.jooq.tables.records.SpecialtyRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.specialty.name</code>.
	 */
	public final org.jooq.TableField<maxicmd.jooq.tables.records.SpecialtyRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(255).defaulted(true), this, "");

	/**
	 * Create a <code>public.specialty</code> table reference
	 */
	public Specialty() {
		this("specialty", null);
	}

	/**
	 * Create an aliased <code>public.specialty</code> table reference
	 */
	public Specialty(java.lang.String alias) {
		this(alias, maxicmd.jooq.tables.Specialty.SPECIALTY);
	}

	private Specialty(java.lang.String alias, org.jooq.Table<maxicmd.jooq.tables.records.SpecialtyRecord> aliased) {
		this(alias, aliased, null);
	}

	private Specialty(java.lang.String alias, org.jooq.Table<maxicmd.jooq.tables.records.SpecialtyRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, maxicmd.jooq.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<maxicmd.jooq.tables.records.SpecialtyRecord> getPrimaryKey() {
		return maxicmd.jooq.Keys.SPECIALITY_PK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<maxicmd.jooq.tables.records.SpecialtyRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<maxicmd.jooq.tables.records.SpecialtyRecord>>asList(maxicmd.jooq.Keys.SPECIALITY_PK);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public maxicmd.jooq.tables.Specialty as(java.lang.String alias) {
		return new maxicmd.jooq.tables.Specialty(alias, this);
	}

	/**
	 * Rename this table
	 */
	public maxicmd.jooq.tables.Specialty rename(java.lang.String name) {
		return new maxicmd.jooq.tables.Specialty(name, null);
	}
}
