/**
 * This class is generated by jOOQ
 */
package maxicmd.jooq.information_schema.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InDoubt extends org.jooq.impl.TableImpl<maxicmd.jooq.information_schema.tables.records.InDoubtRecord> {

	private static final long serialVersionUID = 783352885;

	/**
	 * The singleton instance of <code>INFORMATION_SCHEMA.IN_DOUBT</code>
	 */
	public static final maxicmd.jooq.information_schema.tables.InDoubt IN_DOUBT = new maxicmd.jooq.information_schema.tables.InDoubt();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<maxicmd.jooq.information_schema.tables.records.InDoubtRecord> getRecordType() {
		return maxicmd.jooq.information_schema.tables.records.InDoubtRecord.class;
	}

	/**
	 * The column <code>INFORMATION_SCHEMA.IN_DOUBT.TRANSACTION</code>.
	 */
	public final org.jooq.TableField<maxicmd.jooq.information_schema.tables.records.InDoubtRecord, java.lang.String> TRANSACTION = createField("TRANSACTION", org.jooq.impl.SQLDataType.VARCHAR.length(2147483647), this, "");

	/**
	 * The column <code>INFORMATION_SCHEMA.IN_DOUBT.STATE</code>.
	 */
	public final org.jooq.TableField<maxicmd.jooq.information_schema.tables.records.InDoubtRecord, java.lang.String> STATE = createField("STATE", org.jooq.impl.SQLDataType.VARCHAR.length(2147483647), this, "");

	/**
	 * Create a <code>INFORMATION_SCHEMA.IN_DOUBT</code> table reference
	 */
	public InDoubt() {
		this("IN_DOUBT", null);
	}

	/**
	 * Create an aliased <code>INFORMATION_SCHEMA.IN_DOUBT</code> table reference
	 */
	public InDoubt(java.lang.String alias) {
		this(alias, maxicmd.jooq.information_schema.tables.InDoubt.IN_DOUBT);
	}

	private InDoubt(java.lang.String alias, org.jooq.Table<maxicmd.jooq.information_schema.tables.records.InDoubtRecord> aliased) {
		this(alias, aliased, null);
	}

	private InDoubt(java.lang.String alias, org.jooq.Table<maxicmd.jooq.information_schema.tables.records.InDoubtRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, maxicmd.jooq.information_schema.InformationSchema.INFORMATION_SCHEMA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public maxicmd.jooq.information_schema.tables.InDoubt as(java.lang.String alias) {
		return new maxicmd.jooq.information_schema.tables.InDoubt(alias, this);
	}

	/**
	 * Rename this table
	 */
	public maxicmd.jooq.information_schema.tables.InDoubt rename(java.lang.String name) {
		return new maxicmd.jooq.information_schema.tables.InDoubt(name, null);
	}
}
