/**
 * This class is generated by jOOQ
 */
package maxicmd.jooq.information_schema.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Roles extends org.jooq.impl.TableImpl<maxicmd.jooq.information_schema.tables.records.RolesRecord> {

	private static final long serialVersionUID = -245526241;

	/**
	 * The singleton instance of <code>INFORMATION_SCHEMA.ROLES</code>
	 */
	public static final maxicmd.jooq.information_schema.tables.Roles ROLES = new maxicmd.jooq.information_schema.tables.Roles();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<maxicmd.jooq.information_schema.tables.records.RolesRecord> getRecordType() {
		return maxicmd.jooq.information_schema.tables.records.RolesRecord.class;
	}

	/**
	 * The column <code>INFORMATION_SCHEMA.ROLES.NAME</code>.
	 */
	public final org.jooq.TableField<maxicmd.jooq.information_schema.tables.records.RolesRecord, java.lang.String> NAME = createField("NAME", org.jooq.impl.SQLDataType.VARCHAR.length(2147483647), this, "");

	/**
	 * The column <code>INFORMATION_SCHEMA.ROLES.REMARKS</code>.
	 */
	public final org.jooq.TableField<maxicmd.jooq.information_schema.tables.records.RolesRecord, java.lang.String> REMARKS = createField("REMARKS", org.jooq.impl.SQLDataType.VARCHAR.length(2147483647), this, "");

	/**
	 * The column <code>INFORMATION_SCHEMA.ROLES.ID</code>.
	 */
	public final org.jooq.TableField<maxicmd.jooq.information_schema.tables.records.RolesRecord, java.lang.Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * Create a <code>INFORMATION_SCHEMA.ROLES</code> table reference
	 */
	public Roles() {
		this("ROLES", null);
	}

	/**
	 * Create an aliased <code>INFORMATION_SCHEMA.ROLES</code> table reference
	 */
	public Roles(java.lang.String alias) {
		this(alias, maxicmd.jooq.information_schema.tables.Roles.ROLES);
	}

	private Roles(java.lang.String alias, org.jooq.Table<maxicmd.jooq.information_schema.tables.records.RolesRecord> aliased) {
		this(alias, aliased, null);
	}

	private Roles(java.lang.String alias, org.jooq.Table<maxicmd.jooq.information_schema.tables.records.RolesRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, maxicmd.jooq.information_schema.InformationSchema.INFORMATION_SCHEMA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public maxicmd.jooq.information_schema.tables.Roles as(java.lang.String alias) {
		return new maxicmd.jooq.information_schema.tables.Roles(alias, this);
	}

	/**
	 * Rename this table
	 */
	public maxicmd.jooq.information_schema.tables.Roles rename(java.lang.String name) {
		return new maxicmd.jooq.information_schema.tables.Roles(name, null);
	}
}
