/**
 * This class is generated by jOOQ
 */
package maxicmd.jooq.information_schema;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in INFORMATION_SCHEMA
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table INFORMATION_SCHEMA.QUERY_STATISTICS
	 */
	public static final maxicmd.jooq.information_schema.tables.QueryStatistics QUERY_STATISTICS = maxicmd.jooq.information_schema.tables.QueryStatistics.QUERY_STATISTICS;

	/**
	 * The table INFORMATION_SCHEMA.SESSION_STATE
	 */
	public static final maxicmd.jooq.information_schema.tables.SessionState SESSION_STATE = maxicmd.jooq.information_schema.tables.SessionState.SESSION_STATE;

	/**
	 * The table INFORMATION_SCHEMA.LOCKS
	 */
	public static final maxicmd.jooq.information_schema.tables.Locks LOCKS = maxicmd.jooq.information_schema.tables.Locks.LOCKS;

	/**
	 * The table INFORMATION_SCHEMA.SESSIONS
	 */
	public static final maxicmd.jooq.information_schema.tables.Sessions SESSIONS = maxicmd.jooq.information_schema.tables.Sessions.SESSIONS;

	/**
	 * The table INFORMATION_SCHEMA.TRIGGERS
	 */
	public static final maxicmd.jooq.information_schema.tables.Triggers TRIGGERS = maxicmd.jooq.information_schema.tables.Triggers.TRIGGERS;

	/**
	 * The table INFORMATION_SCHEMA.DOMAINS
	 */
	public static final maxicmd.jooq.information_schema.tables.Domains DOMAINS = maxicmd.jooq.information_schema.tables.Domains.DOMAINS;

	/**
	 * The table INFORMATION_SCHEMA.CONSTANTS
	 */
	public static final maxicmd.jooq.information_schema.tables.Constants CONSTANTS = maxicmd.jooq.information_schema.tables.Constants.CONSTANTS;

	/**
	 * The table INFORMATION_SCHEMA.FUNCTION_COLUMNS
	 */
	public static final maxicmd.jooq.information_schema.tables.FunctionColumns FUNCTION_COLUMNS = maxicmd.jooq.information_schema.tables.FunctionColumns.FUNCTION_COLUMNS;

	/**
	 * The table INFORMATION_SCHEMA.CONSTRAINTS
	 */
	public static final maxicmd.jooq.information_schema.tables.Constraints CONSTRAINTS = maxicmd.jooq.information_schema.tables.Constraints.CONSTRAINTS;

	/**
	 * The table INFORMATION_SCHEMA.CROSS_REFERENCES
	 */
	public static final maxicmd.jooq.information_schema.tables.CrossReferences CROSS_REFERENCES = maxicmd.jooq.information_schema.tables.CrossReferences.CROSS_REFERENCES;

	/**
	 * The table INFORMATION_SCHEMA.IN_DOUBT
	 */
	public static final maxicmd.jooq.information_schema.tables.InDoubt IN_DOUBT = maxicmd.jooq.information_schema.tables.InDoubt.IN_DOUBT;

	/**
	 * The table INFORMATION_SCHEMA.VIEWS
	 */
	public static final maxicmd.jooq.information_schema.tables.Views VIEWS = maxicmd.jooq.information_schema.tables.Views.VIEWS;

	/**
	 * The table INFORMATION_SCHEMA.COLLATIONS
	 */
	public static final maxicmd.jooq.information_schema.tables.Collations COLLATIONS = maxicmd.jooq.information_schema.tables.Collations.COLLATIONS;

	/**
	 * The table INFORMATION_SCHEMA.COLUMN_PRIVILEGES
	 */
	public static final maxicmd.jooq.information_schema.tables.ColumnPrivileges COLUMN_PRIVILEGES = maxicmd.jooq.information_schema.tables.ColumnPrivileges.COLUMN_PRIVILEGES;

	/**
	 * The table INFORMATION_SCHEMA.TABLE_PRIVILEGES
	 */
	public static final maxicmd.jooq.information_schema.tables.TablePrivileges TABLE_PRIVILEGES = maxicmd.jooq.information_schema.tables.TablePrivileges.TABLE_PRIVILEGES;

	/**
	 * The table INFORMATION_SCHEMA.SCHEMATA
	 */
	public static final maxicmd.jooq.information_schema.tables.Schemata SCHEMATA = maxicmd.jooq.information_schema.tables.Schemata.SCHEMATA;

	/**
	 * The table INFORMATION_SCHEMA.FUNCTION_ALIASES
	 */
	public static final maxicmd.jooq.information_schema.tables.FunctionAliases FUNCTION_ALIASES = maxicmd.jooq.information_schema.tables.FunctionAliases.FUNCTION_ALIASES;

	/**
	 * The table INFORMATION_SCHEMA.RIGHTS
	 */
	public static final maxicmd.jooq.information_schema.tables.Rights RIGHTS = maxicmd.jooq.information_schema.tables.Rights.RIGHTS;

	/**
	 * The table INFORMATION_SCHEMA.ROLES
	 */
	public static final maxicmd.jooq.information_schema.tables.Roles ROLES = maxicmd.jooq.information_schema.tables.Roles.ROLES;

	/**
	 * The table INFORMATION_SCHEMA.USERS
	 */
	public static final maxicmd.jooq.information_schema.tables.Users USERS = maxicmd.jooq.information_schema.tables.Users.USERS;

	/**
	 * The table INFORMATION_SCHEMA.SEQUENCES
	 */
	public static final maxicmd.jooq.information_schema.tables.Sequences SEQUENCES = maxicmd.jooq.information_schema.tables.Sequences.SEQUENCES;

	/**
	 * The table INFORMATION_SCHEMA.HELP
	 */
	public static final maxicmd.jooq.information_schema.tables.Help HELP = maxicmd.jooq.information_schema.tables.Help.HELP;

	/**
	 * The table INFORMATION_SCHEMA.SETTINGS
	 */
	public static final maxicmd.jooq.information_schema.tables.Settings SETTINGS = maxicmd.jooq.information_schema.tables.Settings.SETTINGS;

	/**
	 * The table INFORMATION_SCHEMA.CATALOGS
	 */
	public static final maxicmd.jooq.information_schema.tables.Catalogs CATALOGS = maxicmd.jooq.information_schema.tables.Catalogs.CATALOGS;

	/**
	 * The table INFORMATION_SCHEMA.TYPE_INFO
	 */
	public static final maxicmd.jooq.information_schema.tables.TypeInfo TYPE_INFO = maxicmd.jooq.information_schema.tables.TypeInfo.TYPE_INFO;

	/**
	 * The table INFORMATION_SCHEMA.TABLE_TYPES
	 */
	public static final maxicmd.jooq.information_schema.tables.TableTypes TABLE_TYPES = maxicmd.jooq.information_schema.tables.TableTypes.TABLE_TYPES;

	/**
	 * The table INFORMATION_SCHEMA.INDEXES
	 */
	public static final maxicmd.jooq.information_schema.tables.Indexes INDEXES = maxicmd.jooq.information_schema.tables.Indexes.INDEXES;

	/**
	 * The table INFORMATION_SCHEMA.COLUMNS
	 */
	public static final maxicmd.jooq.information_schema.tables.Columns COLUMNS = maxicmd.jooq.information_schema.tables.Columns.COLUMNS;

	/**
	 * The table INFORMATION_SCHEMA.TABLES
	 */
	public static final maxicmd.jooq.information_schema.tables.Tables TABLES = maxicmd.jooq.information_schema.tables.Tables.TABLES;
}
