/**
 * This class is generated by jOOQ
 */
package maxicmd.jooq.public_.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AthletesRecord extends org.jooq.impl.UpdatableRecordImpl<maxicmd.jooq.public_.tables.records.AthletesRecord> {

	private static final long serialVersionUID = 2085741719;

	/**
	 * Setter for <code>PUBLIC.ATHLETES.NAME</code>.
	 */
	public void setName(java.lang.String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>PUBLIC.ATHLETES.NAME</code>.
	 */
	public java.lang.String getName() {
		return (java.lang.String) getValue(0);
	}

	/**
	 * Setter for <code>PUBLIC.ATHLETES.SURNAME</code>.
	 */
	public void setSurname(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>PUBLIC.ATHLETES.SURNAME</code>.
	 */
	public java.lang.String getSurname() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>PUBLIC.ATHLETES.SEX</code>.
	 */
	public void setSex(java.lang.Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>PUBLIC.ATHLETES.SEX</code>.
	 */
	public java.lang.Integer getSex() {
		return (java.lang.Integer) getValue(2);
	}

	/**
	 * Setter for <code>PUBLIC.ATHLETES.AGE</code>.
	 */
	public void setAge(java.lang.Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>PUBLIC.ATHLETES.AGE</code>.
	 */
	public java.lang.Integer getAge() {
		return (java.lang.Integer) getValue(3);
	}

	/**
	 * Setter for <code>PUBLIC.ATHLETES.NATIONID</code>.
	 */
	public void setNationid(java.lang.Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>PUBLIC.ATHLETES.NATIONID</code>.
	 */
	public java.lang.Integer getNationid() {
		return (java.lang.Integer) getValue(4);
	}

	/**
	 * Setter for <code>PUBLIC.ATHLETES.OWNER</code>.
	 */
	public void setOwner(java.lang.Integer value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>PUBLIC.ATHLETES.OWNER</code>.
	 */
	public java.lang.Integer getOwner() {
		return (java.lang.Integer) getValue(5);
	}

	/**
	 * Setter for <code>PUBLIC.ATHLETES.WAGE</code>.
	 */
	public void setWage(java.lang.Integer value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>PUBLIC.ATHLETES.WAGE</code>.
	 */
	public java.lang.Integer getWage() {
		return (java.lang.Integer) getValue(6);
	}

	/**
	 * Setter for <code>PUBLIC.ATHLETES.HEIGHT</code>.
	 */
	public void setHeight(java.lang.Integer value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>PUBLIC.ATHLETES.HEIGHT</code>.
	 */
	public java.lang.Integer getHeight() {
		return (java.lang.Integer) getValue(7);
	}

	/**
	 * Setter for <code>PUBLIC.ATHLETES.WEIGHT</code>.
	 */
	public void setWeight(java.lang.Integer value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>PUBLIC.ATHLETES.WEIGHT</code>.
	 */
	public java.lang.Integer getWeight() {
		return (java.lang.Integer) getValue(8);
	}

	/**
	 * Setter for <code>PUBLIC.ATHLETES.FANS</code>.
	 */
	public void setFans(java.lang.Integer value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>PUBLIC.ATHLETES.FANS</code>.
	 */
	public java.lang.Integer getFans() {
		return (java.lang.Integer) getValue(9);
	}

	/**
	 * Setter for <code>PUBLIC.ATHLETES.SPONSOR</code>.
	 */
	public void setSponsor(java.lang.Integer value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>PUBLIC.ATHLETES.SPONSOR</code>.
	 */
	public java.lang.Integer getSponsor() {
		return (java.lang.Integer) getValue(10);
	}

	/**
	 * Setter for <code>PUBLIC.ATHLETES.MAXID</code>.
	 */
	public void setMaxid(java.lang.Integer value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>PUBLIC.ATHLETES.MAXID</code>.
	 */
	public java.lang.Integer getMaxid() {
		return (java.lang.Integer) getValue(11);
	}

	/**
	 * Setter for <code>PUBLIC.ATHLETES.FORM</code>.
	 */
	public void setForm(java.lang.Integer value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>PUBLIC.ATHLETES.FORM</code>.
	 */
	public java.lang.Integer getForm() {
		return (java.lang.Integer) getValue(12);
	}

	/**
	 * Setter for <code>PUBLIC.ATHLETES.CARE</code>.
	 */
	public void setCare(java.lang.Integer value) {
		setValue(13, value);
	}

	/**
	 * Getter for <code>PUBLIC.ATHLETES.CARE</code>.
	 */
	public java.lang.Integer getCare() {
		return (java.lang.Integer) getValue(13);
	}

	/**
	 * Setter for <code>PUBLIC.ATHLETES.EXPERIENCE</code>.
	 */
	public void setExperience(java.lang.Integer value) {
		setValue(14, value);
	}

	/**
	 * Getter for <code>PUBLIC.ATHLETES.EXPERIENCE</code>.
	 */
	public java.lang.Integer getExperience() {
		return (java.lang.Integer) getValue(14);
	}

	/**
	 * Setter for <code>PUBLIC.ATHLETES.MOOD</code>.
	 */
	public void setMood(java.lang.Integer value) {
		setValue(15, value);
	}

	/**
	 * Getter for <code>PUBLIC.ATHLETES.MOOD</code>.
	 */
	public java.lang.Integer getMood() {
		return (java.lang.Integer) getValue(15);
	}

	/**
	 * Setter for <code>PUBLIC.ATHLETES.SPECIALTYID</code>.
	 */
	public void setSpecialtyid(java.lang.Integer value) {
		setValue(16, value);
	}

	/**
	 * Getter for <code>PUBLIC.ATHLETES.SPECIALTYID</code>.
	 */
	public java.lang.Integer getSpecialtyid() {
		return (java.lang.Integer) getValue(16);
	}

	/**
	 * Setter for <code>PUBLIC.ATHLETES.FAVORITEEVENTID</code>.
	 */
	public void setFavoriteeventid(java.lang.Integer value) {
		setValue(17, value);
	}

	/**
	 * Getter for <code>PUBLIC.ATHLETES.FAVORITEEVENTID</code>.
	 */
	public java.lang.Integer getFavoriteeventid() {
		return (java.lang.Integer) getValue(17);
	}

	/**
	 * Setter for <code>PUBLIC.ATHLETES.STRENGHT</code>.
	 */
	public void setStrenght(java.lang.Integer value) {
		setValue(18, value);
	}

	/**
	 * Getter for <code>PUBLIC.ATHLETES.STRENGHT</code>.
	 */
	public java.lang.Integer getStrenght() {
		return (java.lang.Integer) getValue(18);
	}

	/**
	 * Setter for <code>PUBLIC.ATHLETES.STAMINA</code>.
	 */
	public void setStamina(java.lang.Integer value) {
		setValue(19, value);
	}

	/**
	 * Getter for <code>PUBLIC.ATHLETES.STAMINA</code>.
	 */
	public java.lang.Integer getStamina() {
		return (java.lang.Integer) getValue(19);
	}

	/**
	 * Setter for <code>PUBLIC.ATHLETES.SPEED</code>.
	 */
	public void setSpeed(java.lang.Integer value) {
		setValue(20, value);
	}

	/**
	 * Getter for <code>PUBLIC.ATHLETES.SPEED</code>.
	 */
	public java.lang.Integer getSpeed() {
		return (java.lang.Integer) getValue(20);
	}

	/**
	 * Setter for <code>PUBLIC.ATHLETES.AGILITY</code>.
	 */
	public void setAgility(java.lang.Integer value) {
		setValue(21, value);
	}

	/**
	 * Getter for <code>PUBLIC.ATHLETES.AGILITY</code>.
	 */
	public java.lang.Integer getAgility() {
		return (java.lang.Integer) getValue(21);
	}

	/**
	 * Setter for <code>PUBLIC.ATHLETES.JUMP</code>.
	 */
	public void setJump(java.lang.Integer value) {
		setValue(22, value);
	}

	/**
	 * Getter for <code>PUBLIC.ATHLETES.JUMP</code>.
	 */
	public java.lang.Integer getJump() {
		return (java.lang.Integer) getValue(22);
	}

	/**
	 * Setter for <code>PUBLIC.ATHLETES.THROW</code>.
	 */
	public void setThrow(java.lang.Integer value) {
		setValue(23, value);
	}

	/**
	 * Getter for <code>PUBLIC.ATHLETES.THROW</code>.
	 */
	public java.lang.Integer getThrow() {
		return (java.lang.Integer) getValue(23);
	}

	/**
	 * Setter for <code>PUBLIC.ATHLETES.SPECIALTY1</code>.
	 */
	public void setSpecialty1(java.lang.Integer value) {
		setValue(24, value);
	}

	/**
	 * Getter for <code>PUBLIC.ATHLETES.SPECIALTY1</code>.
	 */
	public java.lang.Integer getSpecialty1() {
		return (java.lang.Integer) getValue(24);
	}

	/**
	 * Setter for <code>PUBLIC.ATHLETES.SPECIALTY2</code>.
	 */
	public void setSpecialty2(java.lang.Integer value) {
		setValue(25, value);
	}

	/**
	 * Getter for <code>PUBLIC.ATHLETES.SPECIALTY2</code>.
	 */
	public java.lang.Integer getSpecialty2() {
		return (java.lang.Integer) getValue(25);
	}

	/**
	 * Setter for <code>PUBLIC.ATHLETES.COACHID</code>.
	 */
	public void setCoachid(java.lang.Integer value) {
		setValue(26, value);
	}

	/**
	 * Getter for <code>PUBLIC.ATHLETES.COACHID</code>.
	 */
	public java.lang.Integer getCoachid() {
		return (java.lang.Integer) getValue(26);
	}

	/**
	 * Setter for <code>PUBLIC.ATHLETES.INJURY</code>.
	 */
	public void setInjury(java.lang.Integer value) {
		setValue(27, value);
	}

	/**
	 * Getter for <code>PUBLIC.ATHLETES.INJURY</code>.
	 */
	public java.lang.Integer getInjury() {
		return (java.lang.Integer) getValue(27);
	}

	/**
	 * Setter for <code>PUBLIC.ATHLETES.SELL</code>.
	 */
	public void setSell(java.lang.Integer value) {
		setValue(28, value);
	}

	/**
	 * Getter for <code>PUBLIC.ATHLETES.SELL</code>.
	 */
	public java.lang.Integer getSell() {
		return (java.lang.Integer) getValue(28);
	}

	/**
	 * Setter for <code>PUBLIC.ATHLETES.YOUTH</code>.
	 */
	public void setYouth(java.lang.Integer value) {
		setValue(29, value);
	}

	/**
	 * Getter for <code>PUBLIC.ATHLETES.YOUTH</code>.
	 */
	public java.lang.Integer getYouth() {
		return (java.lang.Integer) getValue(29);
	}

	/**
	 * Setter for <code>PUBLIC.ATHLETES.SPECIALTYIDTRAINED</code>.
	 */
	public void setSpecialtyidtrained(java.lang.Integer value) {
		setValue(30, value);
	}

	/**
	 * Getter for <code>PUBLIC.ATHLETES.SPECIALTYIDTRAINED</code>.
	 */
	public java.lang.Integer getSpecialtyidtrained() {
		return (java.lang.Integer) getValue(30);
	}

	/**
	 * Setter for <code>PUBLIC.ATHLETES.DIET</code>.
	 */
	public void setDiet(java.lang.Integer value) {
		setValue(31, value);
	}

	/**
	 * Getter for <code>PUBLIC.ATHLETES.DIET</code>.
	 */
	public java.lang.Integer getDiet() {
		return (java.lang.Integer) getValue(31);
	}

	/**
	 * Setter for <code>PUBLIC.ATHLETES.TRAININGRETREAT</code>.
	 */
	public void setTrainingretreat(java.lang.Integer value) {
		setValue(32, value);
	}

	/**
	 * Getter for <code>PUBLIC.ATHLETES.TRAININGRETREAT</code>.
	 */
	public java.lang.Integer getTrainingretreat() {
		return (java.lang.Integer) getValue(32);
	}

	/**
	 * Setter for <code>PUBLIC.ATHLETES.ATHLETEID</code>.
	 */
	public void setAthleteid(java.lang.Integer value) {
		setValue(33, value);
	}

	/**
	 * Getter for <code>PUBLIC.ATHLETES.ATHLETEID</code>.
	 */
	public java.lang.Integer getAthleteid() {
		return (java.lang.Integer) getValue(33);
	}

	/**
	 * Setter for <code>PUBLIC.ATHLETES.ID</code>.
	 */
	public void setId(java.lang.Long value) {
		setValue(34, value);
	}

	/**
	 * Getter for <code>PUBLIC.ATHLETES.ID</code>.
	 */
	public java.lang.Long getId() {
		return (java.lang.Long) getValue(34);
	}

	/**
	 * Setter for <code>PUBLIC.ATHLETES.CREATED</code>.
	 */
	public void setCreated(java.sql.Timestamp value) {
		setValue(35, value);
	}

	/**
	 * Getter for <code>PUBLIC.ATHLETES.CREATED</code>.
	 */
	public java.sql.Timestamp getCreated() {
		return (java.sql.Timestamp) getValue(35);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Long> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached AthletesRecord
	 */
	public AthletesRecord() {
		super(maxicmd.jooq.public_.tables.Athletes.ATHLETES);
	}

	/**
	 * Create a detached, initialised AthletesRecord
	 */
	public AthletesRecord(java.lang.String name, java.lang.String surname, java.lang.Integer sex, java.lang.Integer age, java.lang.Integer nationid, java.lang.Integer owner, java.lang.Integer wage, java.lang.Integer height, java.lang.Integer weight, java.lang.Integer fans, java.lang.Integer sponsor, java.lang.Integer maxid, java.lang.Integer form, java.lang.Integer care, java.lang.Integer experience, java.lang.Integer mood, java.lang.Integer specialtyid, java.lang.Integer favoriteeventid, java.lang.Integer strenght, java.lang.Integer stamina, java.lang.Integer speed, java.lang.Integer agility, java.lang.Integer jump, java.lang.Integer throw_, java.lang.Integer specialty1, java.lang.Integer specialty2, java.lang.Integer coachid, java.lang.Integer injury, java.lang.Integer sell, java.lang.Integer youth, java.lang.Integer specialtyidtrained, java.lang.Integer diet, java.lang.Integer trainingretreat, java.lang.Integer athleteid, java.lang.Long id, java.sql.Timestamp created) {
		super(maxicmd.jooq.public_.tables.Athletes.ATHLETES);

		setValue(0, name);
		setValue(1, surname);
		setValue(2, sex);
		setValue(3, age);
		setValue(4, nationid);
		setValue(5, owner);
		setValue(6, wage);
		setValue(7, height);
		setValue(8, weight);
		setValue(9, fans);
		setValue(10, sponsor);
		setValue(11, maxid);
		setValue(12, form);
		setValue(13, care);
		setValue(14, experience);
		setValue(15, mood);
		setValue(16, specialtyid);
		setValue(17, favoriteeventid);
		setValue(18, strenght);
		setValue(19, stamina);
		setValue(20, speed);
		setValue(21, agility);
		setValue(22, jump);
		setValue(23, throw_);
		setValue(24, specialty1);
		setValue(25, specialty2);
		setValue(26, coachid);
		setValue(27, injury);
		setValue(28, sell);
		setValue(29, youth);
		setValue(30, specialtyidtrained);
		setValue(31, diet);
		setValue(32, trainingretreat);
		setValue(33, athleteid);
		setValue(34, id);
		setValue(35, created);
	}
}
