/**
 * This class is generated by jOOQ
 */
package maxicmd.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ImportHistoryRecord extends org.jooq.impl.UpdatableRecordImpl<maxicmd.jooq.tables.records.ImportHistoryRecord> implements org.jooq.Record3<java.lang.String, java.sql.Timestamp, java.lang.Integer> {

	private static final long serialVersionUID = 2081748844;

	/**
	 * Setter for <code>public.import_history.filename</code>.
	 */
	public void setFilename(java.lang.String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.import_history.filename</code>.
	 */
	public java.lang.String getFilename() {
		return (java.lang.String) getValue(0);
	}

	/**
	 * Setter for <code>public.import_history.timestamp</code>.
	 */
	public void setTimestamp(java.sql.Timestamp value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.import_history.timestamp</code>.
	 */
	public java.sql.Timestamp getTimestamp() {
		return (java.sql.Timestamp) getValue(1);
	}

	/**
	 * Setter for <code>public.import_history.id</code>.
	 */
	public void setId(java.lang.Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.import_history.id</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.String, java.sql.Timestamp, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.String, java.sql.Timestamp, java.lang.Integer> valuesRow() {
		return (org.jooq.Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return maxicmd.jooq.tables.ImportHistory.IMPORT_HISTORY.FILENAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field2() {
		return maxicmd.jooq.tables.ImportHistory.IMPORT_HISTORY.TIMESTAMP;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field3() {
		return maxicmd.jooq.tables.ImportHistory.IMPORT_HISTORY.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getFilename();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value2() {
		return getTimestamp();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value3() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ImportHistoryRecord value1(java.lang.String value) {
		setFilename(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ImportHistoryRecord value2(java.sql.Timestamp value) {
		setTimestamp(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ImportHistoryRecord value3(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ImportHistoryRecord values(java.lang.String value1, java.sql.Timestamp value2, java.lang.Integer value3) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ImportHistoryRecord
	 */
	public ImportHistoryRecord() {
		super(maxicmd.jooq.tables.ImportHistory.IMPORT_HISTORY);
	}

	/**
	 * Create a detached, initialised ImportHistoryRecord
	 */
	public ImportHistoryRecord(java.lang.String filename, java.sql.Timestamp timestamp, java.lang.Integer id) {
		super(maxicmd.jooq.tables.ImportHistory.IMPORT_HISTORY);

		setValue(0, filename);
		setValue(1, timestamp);
		setValue(2, id);
	}
}
